### ISSUE TITLE
Change the format of release branches so it links to Clubhouse

### ISSUE THREAD

**Issue by perfectmak** [Terminal-Systems/tflow#1]
## Current Behaviour
Currently branch names are usually in the format `[hotfix|feat]/{featureId}-{featureShortName}` for example: `hotfix/ch8498-deleteDuplicateEventTypes`, but this format is not recognized by clubhouse and therefore when a PR is created it is not linked to the club house card.

## Expected Behaviour
When a PR is created with an id (a valid clubhouse id), it should be linked to the clubhouse card.

## Proposed Solution
According to clubhouse, there are specific format for a branch name such that it would be linked to a clubhouse issue. See here:

![Screenshot 2019-10-21 at 8 08 57 PM](https://user-images.githubusercontent.com/3120013/67235533-29a05080-f43f-11e9-9116-72a22dbf5521.png)

To fit the format, branch names should be created in the form: `[(hotfix)|(feat)]/{featureId}/{featureShortName}`. This way, the featureId would be parsed by clubhouse and we can have normal linking behaviour.

**Comment by dmerrill6** [comment]
Good catch! Wasn't aware of the Clubhouse syntax. Will send a PR soon, but the tool currently reads the current branch and using the syntax knows where to merge or branch so will need to adapt that piece.
